/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/Contact': RouteRecordInfo<'/Contact', '/Contact', Record<never, never>, Record<never, never>>,
    '/Creations/': RouteRecordInfo<'/Creations/', '/Creations', Record<never, never>, Record<never, never>>,
    '/Creations/Artwork': RouteRecordInfo<'/Creations/Artwork', '/Creations/Artwork', Record<never, never>, Record<never, never>>,
    '/Creations/Clothing': RouteRecordInfo<'/Creations/Clothing', '/Creations/Clothing', Record<never, never>, Record<never, never>>,
    '/Creations/Homemade': RouteRecordInfo<'/Creations/Homemade', '/Creations/Homemade', Record<never, never>, Record<never, never>>,
    '/Creations/Jewelry': RouteRecordInfo<'/Creations/Jewelry', '/Creations/Jewelry', Record<never, never>, Record<never, never>>,
    '/Creations/Limited-Time': RouteRecordInfo<'/Creations/Limited-Time', '/Creations/Limited-Time', Record<never, never>, Record<never, never>>,
    '/FAQ': RouteRecordInfo<'/FAQ', '/FAQ', Record<never, never>, Record<never, never>>,
    '/Refund-Policy': RouteRecordInfo<'/Refund-Policy', '/Refund-Policy', Record<never, never>, Record<never, never>>,
    '/Store': RouteRecordInfo<'/Store', '/Store', Record<never, never>, Record<never, never>>,
  }
}
